### PR TITLE
Add tests for the API

### LINKED ISSUE #142: API overhaul: add tests for the API
Parent issue: https://github.com/torrust/torrust-tracker/issues/141

- Keep the current API behaviour: URLs and response codes.
- Write tests for all endpoints and all cases for each endpoint.
- Refactor to use one struct for each error (rejection). See this [PR](https://github.com/torrust/torrust-tracker/pull/133/files).

### PR DESCRIPTION
**Pull request by josecelano**
Added some tests to the API before changing the web framework to Axum.

### CODE REVIEW

**Comment by josecelano** [comment]
hi, @da2ce7 @WarmBeer this is ready to review. These are the tests I've added:

```s
test tracker_api::for_stats_resources::
    should_allow_getting_tracker_statistics ... ok
    should_not_allow_getting_tracker_statistics_for_unauthenticated_users ... ok
test tracker_api::for_torrent_resources::
    should_allow_getting_a_torrent_info ... ok
    should_allow_getting_torrents ... ok
    should_allow_limiting_the_torrents_in_the_result ... ok
    should_allow_the_torrents_result_pagination ... ok
    should_not_allow_getting_a_torrent_info_for_unauthenticated_users ... ok
    should_not_allow_getting_torrents_for_unauthenticated_users ... ok
test tracker_api::for_whitelisted_torrent_resources::
    should_allow_reload_the_whitelist_from_the_database ... ok
    should_allow_removing_a_torrent_from_the_whitelist ... ok
    should_allow_whitelisting_a_torrent ... ok
    should_allow_whitelisting_a_torrent_that_has_been_already_whitelisted ... ok
    should_not_allow_removing_a_torrent_from_the_whitelist_for_unauthenticated_users ... ok
    should_not_allow_whitelisting_a_torrent_for_unauthenticated_users ... ok
test tracker_api::for_key_resources::
    should_allow_deleting_an_auth_key ... ok
    should_allow_generating_a_new_auth_key ... ok
    should_allow_reloading_keys ... ok
    should_not_allow_deleting_an_auth_key_for_unauthenticated_users ... ok
    should_not_allow_generating_a_new_auth_key_for_unauthenticated_users ... ok
    should_not_allow_reloading_keys_for_unauthenticated_users ... ok 
```

**Comment by josecelano** [comment]
ACK 11259e8a33dbfa0f3d141058c84f13bbe8547f7e

**Comment by josecelano** [comment]
@WarmBeer why do you need to expose the reload whitelist (`GET /api/whitelist/reload`) and keys (`GET /api/keys/reload`) "commands" in the API?

**Comment by mickvandijke** [comment]
> @WarmBeer why do you need to expose the reload whitelist (`GET /api/whitelist/reload`) and keys (`GET /api/keys/reload`) "commands" in the API?

@josecelano ,

These commands are for reloading the states from the database. This is useful when an administrator wants to update the tracker whitelist using the database for example.

**Pull request merged**
