### PR TITLE
chore:[#674] Tracker Checker: Ouput in JSON

### LINKED ISSUE #674: Tracker Checker: Ouput in JSON
Parent issue: https://github.com/torrust/torrust-tracker/issues/669

Currently, the Tracker Checker output is a text like this:

```console
TORRUST_CHECKER_CONFIG='{
    "udp_trackers": ["144.126.245.19:6969"],
    "http_trackers": ["https://tracker.torrust-demo.com"],
    "health_checks": ["https://tracker.torrust-demo.com/health_check"]
}' cargo run --bin tracker_checker

Running checks for trackers ...
UDP trackers ...
✓ - Announce at 144.126.245.19:6969 is OK
✓ - Announce at 144.126.245.19:6969 is OK
HTTP trackers ...
✓ - Announce at https://tracker.torrust-demo.com/ is OK
✓ - Scrape at https://tracker.torrust-demo.com/ is OK
Health checks ...
✓ - Health API at https://tracker.torrust-demo.com/health_check is OK
```

The UDP and HTTP clients use JSON. I should have implemented also this output in JSON because:

- It's also easy to read.
- It can be used for automation.

We could implement the new format in JSON and make it the default one. And remove the current `text` format.

The new format could be:

```json
{
  "udp_trackers": [
    {
      "url": "127.0.0.1:6969",
      "status": {
        "code": "ok",
        "message": "",
      }
    },
    {
      "url": "127.0.0.1:6868",
      "status": {
        "code": "error",
        "message": "Can't connect to the UDP server.",
      }
    },
  ],
  "http_trackers": [
    {
      "url": "http://127.0.0.1:7070",
      "status": {
        "code": "ok",
        "message": "",
      }
    },
    {
      "url": "http:://127.0.0.1:7171",
      "status": {
        "code": "error",
        "message": "Can't connect to the HTTP server. Connection rejected.";
      }
    },
  ],
  "health_checks": [
    {
      "url": "http://127.0.0.1:1313/health_check",
      "status": {
        "code": "ok",
        "message": "",
      }
    },
    {
      "url": "http:://127.0.0.1:1414/health_check",
      "status": {
        "code": "error",
        "message": "Can't connect to the HTTP server. Connection rejected.",
      }
    },
  ]
}
```

cc @da2ce7

### PR DESCRIPTION
**Pull request by hungfnt**

### CODE REVIEW

**Review by josecelano — CHANGES_REQUESTED** [review]
Hi @ngthhu looks good. Thank you! Just a couple of things.

### Fix formatting errors

https://github.com/torrust/torrust-tracker/actions/runs/8813597282/job/24196746331?pr=810

### Output should be only the json

Command:

```console
cargo run --bin tracker_checker -- --config-path "./share/default/config/tracker_checker.json"
```

Output:

```output
Running checks for trackers ...
{
  "udp_trackers": [
    {
      "url": "127.0.0.1:6969",
      "status": {
        "code": "ok",
        "message": ""
      }
    }
  ],
  "http_trackers": [
    {
      "url": "http://127.0.0.1:7070/",
      "status": {
        "code": "ok",
        "message": ""
      }
    }
  ],
  "health_checks": [
    {
      "url": "http://127.0.0.1:1313/health_check",
      "status": {
        "code": "ok",
        "message": ""
      }
    }
  ]
}
```

Output should not include:

```output
Running checks for trackers ...
```

You should be able to parse the output as a json. For example:

```console
cargo run --bin tracker_checker -- --config-path "./share/default/config/tracker_checker.json"| jq
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.09s
     Running `target/debug/tracker_checker --config-path ./share/default/config/tracker_checker.json`
parse error: Invalid numeric literal at line 1, column 8
thread 'main' panicked at library/std/src/io/stdio.rs:1118:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Review by josecelano — APPROVED** [review]

**Comment by hungfnt** [comment]
Is it good to name a file with a general name like `structs.rs`?

**Comment by josecelano** [comment]
> Is it good to name a file with a general name like `structs.rs`?

Hi @ngthhu, Since it's a small mod and file, I don't see a big problem. In my case, when I read `structs,` I always think they must contain a kind of DTOs.

But, I would probably have named them:

`output` -> the module

```rust
pub struct Output {
    pub url: String,
    pub status: Status,
}

pub struct Status {
    pub code: String,
    pub message: String,
}
```

Or:

`output` -> the module

```rust
pub struct Result {
    pub url: String,
    pub status: Status,
}

pub struct Status {
    pub code: String,
    pub message: String,
}
```

**Comment by josecelano** [comment]
ACK b27f002ac6e2fb21142bc21c1eb6580544c1bf2f

**Pull request merged**
