### PR TITLE
Added tower-http compression as middleware on both HTTP routers

### LINKED ISSUE #326: Add middleware to compress responses
The HTTP tracker and the API do not send a compressed response.

[tower_http::compression](https://docs.rs/tower-http/0.4.0/tower_http/compression/index.html) middleware could be used.

### Links

- https://tokio.rs/blog/2021-07-announcing-axum#middleware

### PR DESCRIPTION
**Pull request by alexohneander**
Modified:
I have added tower-http compression as middleware on both HTTP routers(API, Tracker HTTP).

All tests were run and were okay.

### CODE REVIEW

**Review by da2ce7 — APPROVED** [review]
Looks good to me. Surprisingly Simple!

**Comment by josecelano** [comment]
I've tested manually with the following:

```s
curl -I 'http://127.0.0.1:1212/api/v1/stats?token=MyAccessToken'   -H 'Cache-Control: no-cache'   -H 'Pragma: no-cache'   -H 'Accept-Encoding: gzip'
curl -raw 'http://127.0.0.1:1212/api/v1/stats?token=MyAccessToken'   -H 'Cache-Control: no-cache'   -H 'Pragma: no-cache'   -H 'Accept-Encoding: gzip' --output response.gz
gzip -d response.gz 
```

**Comment by josecelano** [comment]
ACK 22bb98af388e8fe801b174786bfe0bbe49fc85c8

**Comment by alexohneander** [comment]
@josecelano It is also supported brotli
```bash
curl -I 'http://127.0.0.1:1212/api/v1/stats?token=MyAccessToken'   -H 'Cache-Control: no-cache'   -H 'Pragma: no-cache'   -H 'Accept-Encoding: br'
```

**Pull request merged**
