### PR TITLE
ci: coverage workflow pre-build fix

### LINKED ISSUE #904: Running unit test in coverage workflow is failing
https://github.com/torrust/torrust-tracker/actions/runs/9562458284/job/26358873400?pr=897

Error: `Process completed with exit code 143.`

### PR DESCRIPTION
**Pull request by da2ce7**
closes #904

### CODE REVIEW

**Comment by da2ce7** [comment]
ACK 69f40fc8d4c8a7b982d9c659e14d2f8f3cdb94d1

**Comment by josecelano** [comment]
Hi, @da2ce7. Is this PR the patch to this [issue](https://github.com/torrust/torrust-tracker/issues/904)?

**Comment by josecelano** [comment]
> Hi, @da2ce7. Is this PR the patch to this [issue](https://github.com/torrust/torrust-tracker/issues/904)?

Or was this https://github.com/torrust/torrust-tracker/commit/5f3957a5642049c96574e81126df2e665978a518?

**Comment by da2ce7** [comment]
@josecelano  if it works it should close #904

**Comment by da2ce7** [comment]
ACK daeb7cc7756a83657e40121785f2525319be37e1

**Pull request merged**
