### PR TITLE
Full docker support (reorganized)

### LINKED ISSUE #11: Docker Support
Is Docker support planned? A docker container for the tracker and backend/frontend would be amazing.

[https://blog.logrocket.com/packaging-a-rust-web-service-using-docker/](https://blog.logrocket.com/packaging-a-rust-web-service-using-docker/)

### PR DESCRIPTION
**Pull request by josecelano**
Stacked on/Depends on: https://github.com/torrust/torrust-tracker/pull/128

This is a reorganization of [PR-123](https://github.com/torrust/torrust-tracker/pull/123)

- I've reorganised the commits
- I've implemented [Solution 1](https://github.com/torrust/torrust-tracker/discussions/127#discussioncomment-4412081) discussed [here](https://github.com/torrust/torrust-tracker/discussions/127#discussioncomment-4412081). The application can get the configuration from the `config.toml` file or from an env var `TORRUST_TRACKER_CONFIG` with the same content as the `config.toml` file. I think it's the minimum change to deploy the application using docker easily.

The idea is the same as the solution implemented by @Power2All [here](https://github.com/Power2All/torrust-axum/tree/master/docker). But I'm using only one env var. This way, we do not need to change the code if the configuration changes. On the other hand, we are discussing a new implementation for the [settings](https://github.com/torrust/torrust-tracker/discussions/127), and I did not want to implement things that will need to be changed afterwards. I'm also a fan of small steps :-).

## Testing

I have deployed the application to the Digital Ocean App Platform:

https://lobster-app-dc6o9.ondigitalocean.app/api/stats?token=MyAccessToken

with [this PR branch docker image](https://hub.docker.com/layers/josecelano/torrust-tracker/docker-reorganized-pr/images/sha256-d08ccf6183c451910ba3dfb74695108700b1aaa2dd13f85bf6f0bdecc4bf43d9?context=repo).

If you want to test the feature of getting the configuration from an env var locally (without docker):

```s
TORRUST_TRACKER_CONFIG=`cat config.toml` cargo run
```

With docker, you only need to follow the instructions in the README:

## Notes

Digital Ocean App Platform only allows you to expose one port (0.0.0.0:8080). I've deployed it exposing only the API with this configuration:

```toml
log_level = "info"
mode = "public"
db_driver = "Sqlite3"
db_path = "data.db"
announce_interval = 120
min_announce_interval = 120
max_peer_timeout = 900
on_reverse_proxy = false
external_ip = "0.0.0.0"
tracker_usage_statistics = true
persistent_torrent_completed_stat = false
inactive_peer_cleanup_interval = 600
remove_peerless_torrents = true

[[udp_trackers]]
enabled = false
bind_address = "0.0.0.0:6969"

[[http_trackers]]
enabled = false
bind_address = "0.0.0.0:7070"
ssl_enabled = false
ssl_cert_path = ""
ssl_key_path = ""

[http_api]
enabled = true
bind_address = "0.0.0.0:8080"
ssl_enabled = false
ssl_cert_path = ""
ssl_key_path = ""

[http_api.access_tokens]
admin = "MyAccessToken"
```

I suppose you need to create three apps sharing the state with a MySQL service if you want to deploy all the services. You want to do the same if you want to deploy more than one UDP or HTTP tracker.

### CODE REVIEW

**Comment by josecelano** [comment]
ACK 171a37d3c48cd365b987eaf280b73a5f35855e20

**Comment by josecelano** [comment]
@da2ce7 @WarmBeer, if you want, you can review first https://github.com/torrust/torrust-tracker/pull/128, and them I will rebase this one. This one also contains changes in https://github.com/torrust/torrust-tracker/pull/128. Alternatively, you can review only this one and ignore https://github.com/torrust/torrust-tracker/pull/128. I would suggest reviewing first https://github.com/torrust/torrust-tracker/pull/128.

**Comment by josecelano** [comment]
ACK 6851ec5fc1adf206c0baaa20d6201e119c85a4af

**Review by da2ce7 — APPROVED** [review]
ACK 6851ec5fc1adf206c0baaa20d6201e119c85a4af

**Pull request merged**
