### PR TITLE
Crate docs for `shared` module

### LINKED ISSUE #260: crate docs: for `shared`mod
Parent issue: https://github.com/torrust/torrust-tracker/issues/252

Documentation for [shared module](https://github.com/torrust/torrust-tracker/tree/develop/src/shared).

### PR DESCRIPTION
**Pull request by josecelano**
Documentation for the `crate::shared` module.

- [x] `bit_torrent` mod.
- [x] `clock` mod.
- [x] `crypto` mod.

### CODE REVIEW

**Comment by josecelano** [comment]
Hi @da2ce7 @WarmBeer , this is ready to review.

**Review by da2ce7 — COMMENTED** [review]
Hello jose, you may wish to rebase upon: 8746d82c594d1449acfe6a6c21961990c1c31840
And apply the changes in this fixup: df0a9eea4ac2f2026f4a7de6dd423a18f4738dd9

Otherwise really good docs! :)

**Comment by josecelano** [comment]
ACK df0a9eea4ac2f2026f4a7de6dd423a18f4738dd9

**Comment by da2ce7** [comment]
https://github.com/torrust/torrust-tracker/pull/261/commits/df0a9eea4ac2f2026f4a7de6dd423a18f4738dd9 can be squashed into https://github.com/torrust/torrust-tracker/pull/261/commits/0bf13e69903abf31a5bcf20e397787dceff64c93, it adds nothing of value as a interdependent comment.

**Comment by josecelano** [comment]
> Hello jose, you may wish to rebase upon: [8746d82](https://github.com/torrust/torrust-tracker/commit/8746d82c594d1449acfe6a6c21961990c1c31840) And apply the changes in this fixup: [df0a9ee](https://github.com/torrust/torrust-tracker/commit/df0a9eea4ac2f2026f4a7de6dd423a18f4738dd9)
> 
> Otherwise really good docs! :)

Thank you, @da2ce7. I've included your commits! Thank you for[ fixing the comment](8746d82c594d1449acfe6a6c21961990c1c31840) about the "The year 2038 problem". I searched for the i64 overflow without reading the whole article. My comment was a bit inaccurate. From 15 years (2038 - 20233) to 21 times the universe's estimated age of the universe 🤣.

_Many modern systems have been upgraded to measure Unix time with signed [64-bit](https://en.wikipedia.org/wiki/64-bit_computing) integers which will not overflow for 292 billion years, which is approximately 21 times the estimated [age of the universe](https://en.wikipedia.org/wiki/Age_of_the_universe)._

Source: https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by josecelano** [comment]
ACK ddf4dc639bfd591e1862b43fb312b11240f50d51

**Comment by josecelano** [comment]
> [df0a9ee](https://github.com/torrust/torrust-tracker/commit/df0a9eea4ac2f2026f4a7de6dd423a18f4738dd9) can be squashed into [0bf13e6](https://github.com/torrust/torrust-tracker/commit/0bf13e69903abf31a5bcf20e397787dceff64c93), it adds nothing of value as a interdependent comment.

Done.

**Pull request merged**
