### PR TITLE
Ugrade workflow actions

### LINKED ISSUE #165: Upgrade workflow actions to use Node 16
We have this warning on the [CI workflow](https://github.com/torrust/torrust-tracker/blob/develop/.github/workflows/test_build_release.yml):

```text
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions-rs/toolchain@v1, Swatinem/rust-cache@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

For example:

https://github.com/torrust/torrust-tracker/actions/runs/4066640056

I think we need to upgrade workflow actions.

### PR DESCRIPTION
**Pull request by josecelano**

### CODE REVIEW

**Comment by josecelano** [comment]
There is no newer version for [actions-rs/toolchain](https://github.com/marketplace/actions/rust-toolchain)

There is no newer version for [actions-rs/cargo@v1](https://github.com/marketplace/actions/rust-cargo).

It seems [actions-rs](https://github.com/actions-rs) is [unmaintained](https://github.com/actions-rs/toolchain/issues/216) https://github.com/actions-rs/cargo/issues/222. See:

https://github.com/actions-rs/toolchain/issues/216

There are some alternatives: https://github.com/actions-rs/toolchain/issues/216

It seems [dtolnay/rust-toolchain@stable](https://github.com/marketplace/actions/rustup-toolchain-install) is the replacement for `actions-rs/toolchain`

**Comment by josecelano** [comment]
I don't see a replacement for `actions-rs/cargo@v1`. Maybe we should simply use `cargo` instead of an action.

**Comment by josecelano** [comment]
Tokio-rs is using `dtolnay/rust-toolchain@master`. See: https://github.com/tokio-rs/tokio/blob/master/.github/workflows/ci.yml

**Comment by josecelano** [comment]
ACK 42e7e64542a6c570333405c227ca89ba371e6c33

**Comment by da2ce7** [comment]
Looks good to me. :)

**Pull request merged**
