### PR TITLE
Axum HTTP tracker: discarded PR

### PR DESCRIPTION
**Pull request by josecelano**
This PR is a discarded parent PR. We are tracking subtasks for issue #160 within the issue instead of here.

UPDATE: 12/02/2023

### CODE REVIEW

**Comment by josecelano** [comment]
hi @da2ce7 @WarmBeer, since this PR could be too big, I'm working so that it can be merged at any time. If you want, you can review what I've done so far, and I will merge it. I will reopen it later to continue working on the next subtasks.

Right now, both implementations can be executed for testing. The scaffolding for Axum is ready, and I will start implementing endpoints.

**Comment by da2ce7** [comment]
If you wish to part-wise merge this pull request, split out the current work into a new dedicated pull request, then you can merge that one while keeping this pull request open.

**Comment by josecelano** [comment]
> If you wish to part-wise merge this pull request, split out the current work into a new dedicated pull request, then you can merge that one while keeping this pull request open.

hi @da2ce7 @WarmBeer, I've created the new [child PR](https://github.com/torrust/torrust-tracker/pull/180). I will keep this for tracking the implementation of the main issue, but I will create a new PR for each subtask.

**Comment by da2ce7** [comment]
@josecelano  This pull request was automatically merged when we merged #180, it is impossible to reopen, we should make a new parent pull-request.

**Comment by josecelano** [comment]
> @josecelano This pull request was automatically merged when we merged #180, it is impossible to reopen, we should make a new parent pull-request.

Since I'm planning to merge child PRs into `develop`, maybe we could just move the description to the issue. In the end we are using this PR only to track the progress on the main issue. What do you think @da2ce7 ?

It would be different if we were using stacked  PRs.

**Comment by josecelano** [comment]
I've moved the subtask in this PR description to the [issue](https://github.com/torrust/torrust-tracker/issues/160)

**Pull request merged**
