### PR TITLE
Revert unintentional change for auth key generation API endpoint

### LINKED ISSUE #108: API endpoint for keys was accidentally changed
The tracker has an [endpoint to generate new keys](https://github.com/torrust/torrust-tracker/blob/develop/src/api/server.rs#L260-L278).

The response for that endpoint was like:

```json
{
  "key": "IaWDneuFNZi8IB4MPA3qW1CD0M30EZSM",
  "valid_until": 1674804892
}
```

But now is like this:

```json
{
  "key": "IaWDneuFNZi8IB4MPA3qW1CD0M30EZSM",
  "valid_until": 
    { 
      "secs": 1674804892, 
      "nanos": 423855037
    }
}
```

The change was introduced in this commit cab093c026cf253ba6f7208211953a25b3d1c91b by @da2ce7.

The struct:

```rust
pub struct AuthKey {
    pub key: String,
    pub valid_until: Option<u64>,
 }
```

changed to:

```rust
pub struct AuthKey {
    pub key: String,
    pub valid_until: Option<DurationSinceUnixEpoch>,
}
```

Since we automatically build the json objects exposed in the API, that change was exposed to API consumers.

This change affected the [backend](More info: https://github.com/torrust/torrust-index-backend/issues/78).

### PR DESCRIPTION
**Pull request by josecelano**
Tasks:

- [x] Revert change.
- [x] E2E test for the endpoint.

### CODE REVIEW

**Comment by josecelano** [comment]
hi @WarmBeer, I'm trying to add a test for the API endpoint. I'm doing the same as we did for the UDP tracker. I want to run the API and use an HTTP client to make a request to that endpoint.

For some reason I can't connect to the API:

```s
running 1 test
2022-11-22T19:12:06.110254618+00:00 [torrust_tracker::logging][INFO] logging initialized.
2022-11-22T19:12:06.110283885+00:00 [torrust_tracker::jobs::tracker_api][INFO] Starting Torrust API server on: 127.0.0.1:55790
thread 'tracker_api::should_generate_a_new_auth_key' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(55790), path: "/api/key/60", query: Some("token=MyAccessToken"), fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', tests/api.rs:103:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tracker_api::should_generate_a_new_auth_key ... FAILED
```

The client configuration is correct because it works when I make a request to a manually executed tracker in the standard `1212` port.

I think the problem could be the Tokyo library is not running a new thread for the API and when the client makes the request, the server is not responding. But I do not know if that makes sense. I suppose the server should be executed again when the client is waiting for the response, even is Tokio is using only one thread.

The other problem could be the setup. But It worked for the UDP tracker, and I do not see any error.

Do you have any idea why it's not working or how can I find out the issue? I've run out of ideas.

**Comment by mickvandijke** [comment]
> hi @WarmBeer, I'm trying to add a test for the API endpoint. I'm doing the same as we did for the UDP tracker. I want to run the API and use an HTTP client to make a request to that endpoint.
> 
> For some reason I can't connect to the API:
> 
> ```m68k
> running 1 test
> 2022-11-22T19:12:06.110254618+00:00 [torrust_tracker::logging][INFO] logging initialized.
> 2022-11-22T19:12:06.110283885+00:00 [torrust_tracker::jobs::tracker_api][INFO] Starting Torrust API server on: 127.0.0.1:55790
> thread 'tracker_api::should_generate_a_new_auth_key' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(55790), path: "/api/key/60", query: Some("token=MyAccessToken"), fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', tests/api.rs:103:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> test tracker_api::should_generate_a_new_auth_key ... FAILED
> ```
> 
> The client configuration is correct because it works when I make a request to a manually executed tracker in the standard `1212` port.
> 
> I think the problem could be the Tokyo library is not running a new thread for the API and when the client makes the request, the server is not responding. But I do not know if that makes sense. I suppose the server should be executed again when the client is waiting for the response, even is Tokio is using only one thread.
> 
> The other problem could be the setup. But It worked for the UDP tracker, and I do not see any error.
> 
> Do you have any idea why it's not working or how can I find out the issue? I've run out of ideas.

I will have a look.

**Comment by mickvandijke** [comment]
> hi @WarmBeer, I'm trying to add a test for the API endpoint. I'm doing the same as we did for the UDP tracker. I want to run the API and use an HTTP client to make a request to that endpoint.
> 
> For some reason I can't connect to the API:
> 
> ```m68k
> running 1 test
> 2022-11-22T19:12:06.110254618+00:00 [torrust_tracker::logging][INFO] logging initialized.
> 2022-11-22T19:12:06.110283885+00:00 [torrust_tracker::jobs::tracker_api][INFO] Starting Torrust API server on: 127.0.0.1:55790
> thread 'tracker_api::should_generate_a_new_auth_key' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(55790), path: "/api/key/60", query: Some("token=MyAccessToken"), fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', tests/api.rs:103:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> test tracker_api::should_generate_a_new_auth_key ... FAILED
> ```
> 
> The client configuration is correct because it works when I make a request to a manually executed tracker in the standard `1212` port.
> 
> I think the problem could be the Tokyo library is not running a new thread for the API and when the client makes the request, the server is not responding. But I do not know if that makes sense. I suppose the server should be executed again when the client is waiting for the response, even is Tokio is using only one thread.
> 
> The other problem could be the setup. But It worked for the UDP tracker, and I do not see any error.
> 
> Do you have any idea why it's not working or how can I find out the issue? I've run out of ideas.

Hey Jose,

Somehow the API server is not reachable during the test. I've tried connecting to the test API server from Postman, but I get the same error as Reqwest: "connection refused". 

When running the API manually, it does work like you said. Strange.. 

I have to focus on an issue for the index frontend right now, but I will try again tomorrow if you haven't found a fix by then.

**Comment by josecelano** [comment]
> > hi @WarmBeer, I'm trying to add a test for the API endpoint. I'm doing the same as we did for the UDP tracker. I want to run the API and use an HTTP client to make a request to that endpoint.
> > For some reason I can't connect to the API:
> > ```m68k
> > running 1 test
> > 2022-11-22T19:12:06.110254618+00:00 [torrust_tracker::logging][INFO] logging initialized.
> > 2022-11-22T19:12:06.110283885+00:00 [torrust_tracker::jobs::tracker_api][INFO] Starting Torrust API server on: 127.0.0.1:55790
> > thread 'tracker_api::should_generate_a_new_auth_key' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(55790), path: "/api/key/60", query: Some("token=MyAccessToken"), fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', tests/api.rs:103:14
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > test tracker_api::should_generate_a_new_auth_key ... FAILED
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The client configuration is correct because it works when I make a request to a manually executed tracker in the standard `1212` port.
> > I think the problem could be the Tokyo library is not running a new thread for the API and when the client makes the request, the server is not responding. But I do not know if that makes sense. I suppose the server should be executed again when the client is waiting for the response, even is Tokio is using only one thread.
> > The other problem could be the setup. But It worked for the UDP tracker, and I do not see any error.
> > Do you have any idea why it's not working or how can I find out the issue? I've run out of ideas.
> 
> Hey Jose,
> 
> Somehow the API server is not reachable during the test. I've tried connecting to the test API server from Postman, but I get the same error as Reqwest: "connection refused".
> 
> When running the API manually, it does work like you said. Strange..
> 
> I have to focus on an issue for the index frontend right now, but I will try again tomorrow if you haven't found a fix by then.

Thank you very much @WarmBeer! I've just fixed it [here](https://github.com/torrust/torrust-tracker/pull/109/commits/b316507d29edfd2d6bc445f47a5049151beabec2). It seems we only needed to add a delay to give time to the server to be ready to accept requests. I saw @zupzup added a delay [in this example here](https://github.com/zupzup/rust-web-e2e-testing/blob/1e914d73ced0d5fc0bd766229716dc1825bdda7e/src/tests/mock.rs#L89). Thanks @zupzup for sharing that repo. It's been very helpful for me.

Anyway, I do not like this solution very much because we wait for a random duration, and we make tests slower. Running the test should be a kind of callback executed when the server is ready.

**Comment by josecelano** [comment]
hi @WarmBeer @da2ce7, This is ready for review. I've added a simple e2e test. I was considering using [warp test features](https://docs.rs/warp/0.1.20/warp/test/index.html):

https://docs.rs/warp/0.1.20/warp/test/index.html

but I do not know if it makes sense. It is similar to what other frameworks have. It allows you to test the "controller" without running the web server. In our case, we have a lot of bootstrapping, we have to setup the tracker anyway. I do not know if it is worth it since we only avoid creating the socket (and maybe the setup for the other endpoints).

On the other hand, the e2e test is less coupled with the implementation. I think @WarmBeer wanted to change the web framework. If we change it, we do not need to rewrite the tests.

**Review by da2ce7 — APPROVED** [review]
ACK 92c50e675a1633931571035f1ab670f016af5ff7

**Comment by josecelano** [comment]
> ACK [92c50e6](https://github.com/torrust/torrust-tracker/commit/92c50e675a1633931571035f1ab670f016af5ff7)

@da2ce7 I've rebased to include the latest changes in [PR-111](110).

**Review by da2ce7 — APPROVED** [review]
ACK 409f82af4cb76936da389b37deca05d8321710fa

**Comment by josecelano** [comment]
hi @WarmBeer @da2ce7, I've written an article about the problems I had testing the API endpoint:

https://github.com/Nautilus-Cyberneering/testing-in-rust/blob/main/docs/testing-apis-in-rust.md

While writing the article, I tried different options to avoid the nondeterministic "sleep". I managed to make it work with messages instead of using "sleep".

**Pull request merged**
