### PR TITLE
Refactor: rename peer.updated field in torrent detail endpoint

### LINKED ISSUE #61: Refactor: rename `peer.updated` field in torrent detail endpoint
```rust
pub struct TorrentPeer {
    pub peer_id: PeerId,
    pub peer_addr: SocketAddr,
    #[serde(serialize_with = "ser_instant")]
    pub updated: std::time::Instant,
    #[serde(with = "NumberOfBytesDef")]
    pub uploaded: NumberOfBytes,
    #[serde(with = "NumberOfBytesDef")]
    pub downloaded: NumberOfBytes,
    #[serde(with = "NumberOfBytesDef")]
    pub left: NumberOfBytes,
    #[serde(with = "AnnounceEventDef")]
    pub event: AnnounceEvent,
}
```

@WarmBeer , would not it be nice to rename the `updated` field like this:

```rust
#[serde(serialize_with = "ser_instant")]
#[serde(rename(deserialize = "updated_milliseconds_ago", serialize = "updated_milliseconds_ago"))]
pub updated: std::time::Instant,
```

To get a json like this:

```json
{
  "info_hash": "4beb7001cb833968582c67f55cc59dcc6c8d3fe5",
  "seeders": 1,
  "completed": 0,
  "leechers": 0,
  "peers": [
    {
      "peer_id": {
        "id": "2d7142343431302d7358376d33786d2877674179",
        "client": "qBittorrent"
      },
      "peer_addr": "192.168.1.88:17548",
      "updated_milliseconds_ago": 385,
      "uploaded": 0,
      "downloaded": 0,
      "left": 0,
      "event": "None"
    }
  ]
}
```

I generally like to add the units in the attribute name.

We can use any other name like: `not_updated_duration_in_msecs`, `not_updated_duration_in_msecs`, ...

_Originally posted by @josecelano in https://github.com/torrust/torrust-tracker/issues/60#issuecomment-1210719772_

### PR DESCRIPTION
**Pull request by josecelano**
TODO:

- [x] Add an e2e test before refactoring.
- [x] Refactor the API endpoint to use the resource `TorrentResource` like `AuthKeyResource`.
- [x] Refactor endpoint ` /api/torrents?offset=:u32&limit=:u32` to use `TorrentResource`.
- [x] Add a new field (`updated_milliseconds_ago`) to the JSON response keeping the old one for backwards compatibility.

### CODE REVIEW

**Comment by da2ce7** [comment]
looks good. however this pull-request will conflict much with #115 , we need to choose what one we merge first.

**Comment by josecelano** [comment]
> looks good. however this pull-request will conflict much with #115 , we need to choose what one we merge first.

hi @da2ce7 I think It's probably better if I rework my changes on top of your PR because:
- This PR is smaller.
- Changes are located in very few places and decoupled from the rest.
- There are more additions than modifications. I think the e2e tests for the API won't be affected too much.
- I can also learn about Clipply pedantic warnings fixing them in this PR.

This PR is ready for review, but you can wait until I fix conflicts with your changes. The change was very easy, but I've added e2e tests for many endpoints. I think these tests are good because they cover many things, not only the API layer.

Besides, It will be easy to add more API tests.

**Comment by josecelano** [comment]
> looks good. however this pull-request will conflict much with #115 , we need to choose what one we merge first.

On the other hand 🤔, If we merge first this PR, we are going to have more tests to be sure we have not introduced a regression bug in PR #115.

**Comment by da2ce7** [comment]
> > looks good. however this pull-request will conflict much with #115 , we need to choose what one we merge first.
> 
> On the other hand thinking, If we merge first this PR, we are going to have more tests to be sure we have not introduced a regression bug in PR #115.

Okay, we merge this first. Then I will try and rebase #115  on top of this.  I like having more checks.

**Review by da2ce7 — APPROVED** [review]
ACK e1b84f6eb75dcd9ba0cc6803a0f7221d9b761ef8

**Comment by josecelano** [comment]
ACK e1b84f6eb75dcd9ba0cc6803a0f7221d9b761ef8

**Pull request merged**
