### PR TITLE
Fixing Windows compiling

### LINKED ISSUE #325: Torrust-Tracker won't compile on Windows
Just tried to compile this on Windows CLion with Rust.
These modules are not compatible with Windows:

* ring
* libz-sys
* libsqlite3-sys
* openssl-sys

You might want to look into replacing these, or looking to remove them.
Unless of course, you won't want to support multi-platforms.

### PR DESCRIPTION
**Pull request by Power2All**
Fixing compiling in Windows, was simple.
Now you don't need cmake or any of that.

### CODE REVIEW

**Comment by josecelano** [comment]
ACK 39d0b761366a7cb31b629eccac05b66eff4e5f13

**Comment by josecelano** [comment]
Thank you @Power2All !!!

**Comment by josecelano** [comment]
Hi @Power2All I've open a new PR only to sign the commit: https://github.com/torrust/torrust-tracker/pull/1108. We have set repo rules to only allow signed commits.

**Comment by Power2All** [comment]
> Hi @Power2All I've open a new PR only to sign the commit: #1108. We have set repo rules to only allow signed commits.

Fine with me, only tried to fix the compile issue ;)

**Pull request closed without merging**
